version: 2
updates:
- package-ecosystem: npm
  directory: "/frontend/app"
  schedule:
    interval: daily
    time: "20:00"
  open-pull-requests-limit: 10
  target-branch: develop
  reviewers:
  - yazin
  ignored_updates:
  - match:
    dependency_name: "@types/node"
- package-ecosystem: npm
  directory: "/app"
  schedule:
    interval: daily
    time: "20:00"
  open-pull-requests-limit: 10
  target-branch: develop
  reviewers:
  - yazin
