version: 2
updates:
  - package-ecosystem: npm
    directory: "/frontend/app"
    schedule:
      interval: daily
      time: "20:00"
    open-pull-requests-limit: 10
    target-branch: develop
    reviewers:
      - yazin
    ignore:
      - dependency_name: "@types/node"
        version: ["14.x"]
  - package-ecosystem: npm
    directory: "/app"
    schedule:
      interval: daily
      time: "20:00"
    open-pull-requests-limit: 10
    target-branch: develop
    reviewers:
      - yazin
