version: 2
updates:
  - package-ecosystem: npm
    directory: "/frontend/app"
    schedule:
      interval: daily
      timezone: Asia/Tokyo
      time: "19:00"
    open-pull-requests-limit: 10
    target-branch: develop
    reviewers:
      - yazin
    ignore:
      - dependency-name: "@types/node"
        versions: ["13.x.x", "14.x.x"]
  - package-ecosystem: npm
    directory: "/app"
    schedule:
      interval: daily
      timezone: Asia/Tokyo
      time: "19:00"
    open-pull-requests-limit: 10
    target-branch: develop
    reviewers:
      - yazin
  - package-ecosystem: docker
    directory: "/mysql"
    schedule:
      interval: daily
      timezone: Asia/Tokyo
      time: "19:00"
    open-pull-requests-limit: 10
    target-branch: develop
    reviewers:
      - yazin
