version: '3'
services:
  mysql:
    build: ./mysql
    container_name: flowerstand_mysql
    env_file: ./mysql/mysql.env
    environment: 
      TZ: Asia/Tokyo
    cap_add: 
      - SYS_NICE
    ports:
      - 3306:3306
    volumes:
      - mysqldata:/var/lib/mysql
    networks:
      - flowerstand
  app:
    build: ./app
    container_name: flowerstand_app
    ports:
      - 3000:3000
    volumes:
      - ./app:/app
    command: npm run dev:watch
    networks:
      - flowerstand
    depends_on:
      - mysql
  web:
    build: ./frontend/app
    container_name: flowerstand_web
    ports:
      - 8080:8080
    volumes:
      - ./frontend/app:/app
    command: npm run serve
    networks:
      - flowerstand
    depends_on:
      - app
  nginx:
    build: ./nginx
    container_name: flowerstand_nginx
    volumes:
      - ./frontend/app/dist:/tmp/html
    ports:
      - 80:80
    networks:
      - flowerstand
    depends_on:
      - app
networks: 
  flowerstand:
volumes: 
  mysqldata:
