version: '3'
services:
  mysql:
    image: mysql:8.0.22
    container_name: flowerstand_mysql
    env_file: ./mysql/mysql.env
    environment: 
      TZ: Asia/Tokyo
    cap_add: 
      - SYS_NICE
    ports:
      - 3306:3306
    volumes:
      - ./mysql/conf:/etc/mysql/conf.d/:ro
      - mysqldata:/var/lib/mysql
    networks:
      - flowerstand
  app:
    image: node:12.19.0
    container_name: flowerstand_app
    env_file: ./app/app.env
    environment: 
      TZ: Asia/Tokyo
    ports:
      - 3000:3000
    volumes:
      - ./app:/app
    working_dir: /app
    command: npm run dev:watch
    networks:
      - flowerstand
    depends_on:
      - mysql
  web:
    image: node:12.19.0-alpine
    container_name: flowerstand_web
    environment:
      TZ: Asia/Tokyo
    ports:
      - 8080:8080
    volumes:
      - ./frontend/app:/app
    working_dir: /app
    command: npm run serve
    networks:
      - flowerstand
    depends_on:
      - app
networks: 
  flowerstand:
volumes: 
  mysqldata:
