swagger: '2.0'
info:
  version: 0.0.1
  title: flowerstand
  contact:
    name: Tomoyuki Sato
    url: https://mstdn.schoolidol.club/@yazin
  license:
    name: MIT
    url: http://opensource.org/licenses/MIT
host: localhost:3000
basePath: /api
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
definitions:
  FlowerStand:
    type: object
    properties:
      id:
        type: integer
      name:
        type: string
      presentTo:
        type: string
      presentFrom:
        type: string
      event:
        $ref: "#/definitions/Event"
      description:
        type: string
      projectUrl:
        type: string
      organizerName:
        type: string
      participants:
        type: array
        items: 
          $ref: "#/definitions/Participant"
      baseDesign:
        $ref: "#/definitions/BaseDesign"
      imageUrl:
        type: string
  FlowerStandWithKeys:
    type: object
    properties:
      id:
        type: integer
      name:
        type: string
      presentTo:
        type: string
      presentFrom:
        type: string
      event:
        $ref: "#/definitions/Event"
      description:
        type: string
      projectUrl:
        type: string
      organizerName:
        type: string
      participants:
        type: array
        items: 
          $ref: "#/definitions/Participant"
      baseDesign:
        $ref: "#/definitions/BaseDesign"
      imageUrl:
        type: string
      adminKey:
        type: string
      participationCode:
        type: string
  Participant:
    type: object
    properties:
      id:
        type: integer
      name:
        type: string
      twitterId:
        type: string
      instagramId:
        type: string
      facebookId:
        type: string
      mastodonId:
        type: string
  BaseDesign:
    type: object
    properties:
      id:
        type: integer
      name:
        type: string
      imageUrl:
        type: string
      sortOrder:
        type: integer
      group:
        $ref: "#/definitions/Group"
  Event:
    type: object
    properties:
      id:
        type: integer
      name:
        type: string
      startDate:
        type: string
      endDate:
        type: string
      groups:
        type: array
        items:
          $ref: "#/definitions/Group"
  Group:
    type: object
    properties:
      id:
        type: integer
      name:
        type: string
paths:
  /flowerstands:
    get:
      summary: searches flower stands. returns all flower stands if no parameter specified.
      parameters:
        -
          name: eventId
          in: query
          required: false
          type: integer
        -
          name: baseDesignId
          in: query
          required: false
          type: integer
      responses:
        200:
          description: OK
          schema:
            type: array
            items:
              $ref: "#/definitions/FlowerStand"
    post:
      summary: creates a new flower stand.
      parameters:
        -
          name: flowerStand
          in: body
          required: true
          schema:
            type: object
            properties:
              name:
                type: string
              presentTo:
                type: string
              presentFrom:
                type: string
              organizerName:
                type: string
              description:
                type: string
              projectUrl:
                type: string
              baseDesignId:
                type: integer
              eventId:
                type: integer
              panel:
                type: string
                description: optional illust panel image (jpeg or png), Data URI format.
            required:
              - name
              - presentTo
              - presentFrom
              - organizerName
              - baseDesignId
              - eventId
      responses:
        200:
          description: OK
          schema:
            $ref: "#/definitions/FlowerStandWithKeys"
        204:
          description: baseDesignId or eventId does not exists.
  /flowerstands/verify:
    post:
      summary: verify admin key.
      parameters:
        -
          name: keyData
          in: body
          required: true
          schema:
            type: object
            properties:
              flowerStandId:
                type: integer
              adminKey:
                type: string
            required:
              - flowerStandId
              - adminKey
      responses:
        200:
          description: OK
        204:
          description: flower stand with specified id does not exists.
        401:
          description: invalid adminKey.
  /flowerstands/preview:
    post:
      summary: returns a preview image.
      parameters:
        -
          name: previewData
          in: body
          required: true
          schema:
            type: object
            properties:
              presentTo:
                type: string
              presentFrom:
                type: string
              baseDesignId:
                type: number
              panel:
                type: string
                description: optional illust panel image (jpeg or png), Data URI format.
            required:
              - presentTo
              - presentFrom
              - baseDesignId
      responses:
        200:
          description: OK
          schema:
            type: object
            properties:
              imageUrl:
                type: string
                description: URL of preview image.
  /flowerstands/{id}:
    get:
      summary: returns a flower stand.
      parameters:
        -
          name: id
          in: path
          description: id of flower stand.
          required: true
          type: integer
      responses:
        200:
          description: OK
          schema:
            $ref: "#/definitions/FlowerStand"
        204:
          description: flower stand with specified id does not exists.
    put:
      summary: updates a flower stand.
      parameters:
        -
          name: id
          in: path
          description: id of flower stand to update.
          required: true
          type: integer
        -
          name: flowerStand
          in: body
          required: true
          schema:
            type: object
            properties:
              adminKey:
                type: string
                description: administration key issued on create flower stand.
              name:
                type: string
                description: name of flower stand.
              presentTo:
                type: string
                description: recipient name to be displayed on flower stand.
              presentFrom:
                type: string
                description: presenter name to be displayed on flower stand.
              organizerName:
                type: string
                description: organizer name of flower stand. this is not displayed on flower stand.
              description:
                type: string
                description: description of flower stand.
              projectUrl:
                type: string
                description: URL of flower stand project.
            required:
              - adminKey
      responses:
        200:
          description: OK
        204:
          description: flower stand with specified id does not exists.
        401:
          description: invalid adminKey.
    delete:
      summary: deletes a flower stand.
      parameters:
        -
          name: id
          in: path
          description: id of flower stand to delete.
          required: true
          type: integer
        -
          name: adminKey
          in: query
          description: administration key issued on create flower stand.
          required: true
          type: string
      responses:
        200:
          description: OK
        204:
          description: FlowerStand of specified id does not exists.
        401:
          description: invalid adminKey.
  /basedesigns:
    get:
      summary: returns all base designs.
      responses:
        200:
          description: OK
          schema:
            type: array
            items:
              $ref: "#/definitions/BaseDesign"
  /basedesigns/{id}:
    get:
      summary: returns a base design.
      parameters:
        -
          name: id
          in: path
          description: id of base design.
          required: true
          type: integer
      responses:
        200:
          description: OK
          schema:
            $ref: "#/definitions/BaseDesign"
        204:
          description: base design with specified id not exitsts.
  /events:
    get:
      summary: returns all events.
      responses:
        200:
          description: OK
          schema:
            type: array
            items:
              $ref: "#/definitions/Event"
  /events/{id}:
    get:
      summary: returns a event.
      parameters:
        -
          name: id
          in: path
          description: id of event.
          required: true
          type: integer
      responses:
        200:
          description: OK
          schema:
            $ref: "#/definitions/Event"
        204:
          description: event with specified id does not exists.
  /groups:
    get:
      summary: returns all groups.
      responses:
        200:
          description: OK
          schema:
            type: array
            items: 
              $ref: "#/definitions/Group"
  /groups/{id}:
    get:
      summary: returns a group.
      parameters:
        -
          name: id
          in: path
          description: id of group.
          required: true
          type: integer
      responses:
        200:
          description: OK
          schema:
            $ref: "#/definitions/Group"
        204:
          description: group with specified id does not exists.
  /participants:
    get:
      summary: returns all perticipants for a specified flower stand.
      parameters:
        -
          name: flowerStandId
          in: query
          description: id of flower stand to get participants.
          required: true
          type: integer
      responses:
        200:
          description: OK
          schema:
            $ref: "#/definitions/Participant"
        204:
          description: flower stand with specified id does not exists.
        400:
          description: flowerStandId is not specified or invalid.
    post:
      summary: add a new participant to flower stand.
      parameters:
        -
          name: participant
          in: body
          required: true
          schema:
            type: object
            properties:
              name:
                type: string
              flowerStandId:
                type: integer
              participationCode:
                type: string
              twitterId:
                type: string
              instagramId:
                type: string
              facebookId:
                type: string
              mastodonId:
                type: string
            required:
              - name
              - flowerStandId
              - participationCode
      responses:
        200:
          description: OK
        204:
          description: flower stand with specified id does not exists.
        401:
          description: invalid participationCode.
  /participants/{id}:
    get:
      summary: returns a participant.
      parameters:
        -
          name: id
          in: path
          description: id of participant.
          required: true
          type: integer
      responses:
        200:
          description: OK
          schema:
            $ref: "#/definitions/Participant"
        204:
          description: participant with specified id does not exists.
    delete:
      summary: delete participant from flower stand.
      parameters:
        -
          name: id
          in: path
          description: id of participant to delete.
          required: true
          type: integer
        -
          name: adminKey
          in: query
          description: administration key issued on create flower stand.
          required: true
          type: string
      responses:
        200:
          description: OK
        204:
          description: participant with specified id does not exists.
        401:
          description: invalid adminKey.
